# Generated by Django 3.0 on 2025-04-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_copy_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profile'},
        ),
    ]
